on:
  push:
    tags:
      - "v*"

jobs:
  build-executable:
    permissions: write-all
    name: "Build the platform executable"

    strategy:
      matrix:
        include:
          [
            { os: ubuntu-latest, exe: routology, final: routology.linux },
            { os: macos-latest, exe: routology, final: routology.mac },
            { os: windows-latest, exe: routology.exe, final: routology.exe },
          ]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up the cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: cache-python-packages

      - name: Set up the project
        run: |
          pip install poetry
          pip install pyinstaller
          poetry config virtualenvs.in-project true
          poetry install -vv --without dev

      - name: Build for the platform
        shell: bash
        run: |
          poetry run python bundle.py

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.exe }}
          asset_name: ${{ matrix.final }}
          tag: ${{ github.ref }}
