on:
  push:
    tags:
      - "v*"

jobs:
  build-executable:
    name: "Build the platform executable"

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up the cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: cache-python-packages

      - name: Set up the project
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install -vv --with build
      
      - name: Build for the platform
        shell: bash
        run: |
          poetry run python bundle.py

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          file_glob: true